#!/usr/bin/env sh

cargo_install() {
  cargo install "$1" --force
}

cargo_install 'cargo-update'
cargo_install 'cargo-whatfeatures'
cargo_install 'hyperfine'
cargo_install 'cargo-edit'
cargo_install 'cargo-asm'
cargo_install 'uq'
cargo_install 'lagraph'
cargo_install 'sd'
cargo_install 'sheldon'
# simple calculator REPL, similar to bc(1), with syntax highlighting and persistent history
cargo_install 'eva'
cargo_install 'zoxide'
