#!/usr/bin/env sh

fancy_echo() {
  local fmt="$1"; shift

  printf "\n$fmt\n" "$@"
}

function install_binary() {
    local command=$1
    local install_command=$2

    if ! command -v $command >/dev/null; then
        fancy_echo "Installing $command"
        eval $install_command
    else
        fancy_echo "Skipping $command"
    fi
}

install_binary "bun" "curl -fsSL https://bun.sh/install | bash"
install_binary "deno" "curl -fsSL https://deno.land/install.sh | sh"
