#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "Trackpad: enable tap to click for this user and for the login screen"
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true

fancy_echo "Enable full keyboard access for all controls"
  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

fancy_echo "Set a blazingly fast keyboard repeat rate"
  defaults write NSGlobalDomain KeyRepeat -int 0

fancy_echo "Finder: allow text selection in Quick Look"
  defaults write com.apple.finder QLEnableTextSelection -bool true

fancy_echo "Finder: Avoid creating .DS_Store files on network volumes"
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

fancy_echo "Finder: Show All Files"
  defaults write com.apple.finder AppleShowAllFiles YES

fancy_echo "Finder: Show Status Bar"
  defaults write com.apple.finder ShowStatusBar -bool true

fancy_echo "Finder: Show Path Bar"
  defaults write com.apple.finder ShowPathbar -bool true

fancy_echo "Finder: Search Current Folder By Default"
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

fancy_echo "Dock: Set the icon size of Dock items to 36 pixels"
  defaults write com.apple.dock tilesize -int 36

fancy_echo "Dock: Automatically hide and show"
  defaults write com.apple.dock autohide -bool true

fancy_echo "Mission Control: Don't rearrange by use"
  defaults write com.apple.dock mru-spaces -bool false

fancy_echo "Safari: Set home page to about:blank for faster loading"
  defaults write com.apple.Safari HomePage -string "about:blank"

fancy_echo "Safari: Make search banners default to Contains instead of Starts With"
  defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

fancy_echo "Safari: Prevent opening ‘safe’ files automatically after downloading"
  defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

fancy_echo "Safari: Enable debug menu"
  defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
  defaults write com.apple.Safari IncludeDevelopMenu -bool true
  defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
  defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

fancy_echo "Xcode: See how long a build takes"
  defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES

fancy_echo "Xcode: Use all cores to build"
  defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks `sysctl -n hw.ncpu`

fancy_echo "Make Window animations faster"
  defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

fancy_echo "Show icons for hard drives, servers, and removable media on the desktop"
  defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
  defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

fancy_echo "Display all file extensions and disable rename warning"
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

fancy_echo "Mail: Copy email addreses without names"
  defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false
fancy_echo "Mail: Add the keyboard shortcut ⌘ + Enter to send an email"
  defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"
