#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "Trackpad: enable tap to click for this user and for the login screen"
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

fancy_echo "Keyboard: Enable full access for all controls"
  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

fancy_echo "Keyboard: Set a blazingly fast repeat rate"
  defaults write NSGlobalDomain KeyRepeat -int 0
  defaults write NSGlobalDomain InitialKeyRepeat -int 10

fancy_echo "Keyboard: Disable press-and-hold for keys in favor of key repeat"
  defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

fancy_echo "Keyboard: Disable auto-correct"
  defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

fancy_echo "Finder: allow text selection in Quick Look"
  defaults write com.apple.finder QLEnableTextSelection -bool true

fancy_echo "Finder: Avoid creating .DS_Store files on external volumes"
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

fancy_echo "Finder: Show All Files"
  defaults write com.apple.finder AppleShowAllFiles YES

fancy_echo "Finder: Show Status Bar"
  defaults write com.apple.finder ShowStatusBar -bool true

fancy_echo "Finder: Show Path Bar"
  defaults write com.apple.finder ShowPathbar -bool true

fancy_echo "Finder: Search Current Folder By Default"
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

fancy_echo "Finder: Display all file extensions and disable rename warning"
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

fancy_echo "Finder: Show icons for hard drives, servers, and removable media on the desktop"
  defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
  defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

fancy_echo "Finder: Show Info on icon views"
  /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

fancy_echo "Finder: Sort by name"
  /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist

fancy_echo "Finder: Use list view in windows"
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

fancy_echo "Dock: Set the icon size of Dock items to 28 pixels"
  defaults write com.apple.dock tilesize -int 28

fancy_echo "Dock: Automatically hide and show"
  defaults write com.apple.dock autohide -bool true

fancy_echo "Mission Control: Don't rearrange by use"
  defaults write com.apple.dock mru-spaces -bool false

fancy_echo "Safari: Set home page to about:blank for faster loading"
  defaults write com.apple.Safari HomePage -string "about:blank"

fancy_echo "Safari: Make search banners default to Contains instead of Starts With"
  defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

fancy_echo "Safari: Prevent opening 'safe' files automatically after downloading"
  defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

fancy_echo "Safari: Enable debug menu"
  defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
  defaults write com.apple.Safari IncludeDevelopMenu -bool true
  defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
  defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

fancy_echo "Safari: Enable 'Do Not Track'"
  defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

fancy_echo "Xcode: See how long a build takes"
  defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES

fancy_echo "Xcode: Use all cores to build"
  defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks `sysctl -n hw.ncpu`

fancy_echo "Print: Automatically quit printer app once the print jobs complete"
  defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

fancy_echo "Time Machine: Prevent from prompting to use new hard drives as backup volume"
  defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

fancy_echo "Photos: Prevent from opening automatically when devices are plugged in"
  defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

### Third Party Apps ###

fancy_echo "Tweetbot: Bypass t.co URL shortener"
  defaults write com.tapbots.TweetbotMac OpenURLsDirectly -bool true
