#!/bin/sh

. ./shared.sh

# Close any open System Preferences panes
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# # Keep-alive: update existing `sudo` time stamp until `macOS` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# System {{{
info "System"

substep_info "Restart automatically if the computer freezes"
  sudo systemsetup -setrestartfreeze on
# }}}

# Trackpad {{{
info "Trackpad"

substep_info "Enable tap to click for this user and for the login screen"
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# }}}

# Keyboard {{{
info "Keyboard"
substep_info "Enable full access for all controls"
  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

substep_info "Set a blazingly fast repeat rate"
  defaults write NSGlobalDomain KeyRepeat -int 0
  defaults write NSGlobalDomain InitialKeyRepeat -int 10

substep_info "Disable press-and-hold for keys in favor of key repeat"
  defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

substep_info "Disable auto-correct"
  defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

substep_info "Disable smart quotes and dashes"
  defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
  defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
# }}}

# Finder {{{
info "Finder"

substep_info "Allow text selection in Quick Look"
  defaults write com.apple.finder QLEnableTextSelection -bool true

substep_info "Avoid creating .DS_Store files on external volumes"
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

substep_info "Show All Files"
  defaults write com.apple.finder AppleShowAllFiles YES

substep_info "Show Status Bar"
  defaults write com.apple.finder ShowStatusBar -bool true

substep_info "Show Path Bar"
  defaults write com.apple.finder ShowPathbar -bool true

substep_info "Search Current Folder By Default"
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

substep_info "Display all file extensions and disable rename warning"
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

substep_info "Show icons for hard drives, servers, and removable media on the desktop"
  defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
  defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
  defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

substep_info "Show Info on icon views"
  /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

substep_info "Sort by name"
  /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist

substep_info "Use list view in windows"
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

substep_info "Save to disk instead of iCloud"
  defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
# }}}

# Dock {{{
info "Dock"
substep_info "Set the icon size of Dock items to 28 pixels"
  defaults write com.apple.dock tilesize -int 28

substep_info "Automatically hide and show"
  defaults write com.apple.dock autohide -bool true

substep_info "Adjust hide/show animation timings"
  defaults write com.apple.dock autohide-delay -int 0
  defaults write com.apple.dock autohide-time-modifier -float 0.4

substep_info "Only display open apps"
  defaults write com.apple.dock static-only -bool true
# }}}

# Mission Control {{{
info "Mission Control"
substep_info "Don't rearrange by use"
  defaults write com.apple.dock mru-spaces -bool false
# }}}

# Safari {{{
info "Safari"
substep_info "Set home page to about:blank for faster loading"
  defaults write com.apple.Safari HomePage -string "about:blank"

substep_info "Make search banners default to Contains instead of Starts With"
  defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

substep_info "Prevent opening 'safe' files automatically after downloading"
  defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

substep_info "Enable debug menu"
  defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
  defaults write com.apple.Safari IncludeDevelopMenu -bool true
  defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
  defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
  defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

substep_info "Enable 'Do Not Track'"
  defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true
# }}}

# Xcode {{{
info "Xcode"
substep_info "See how long a build takes"
  defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES

substep_info "Use all cores to build"
  defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks `sysctl -n hw.ncpu`

substep_info "Increase number of concurrent tasks"
  defaults write com.apple.dt.Xcode BuildSystemScheduleInherentlyParallelCommandsExclusively -bool NO
  
substep_info "Use Focused Editor"
  defaults write com.apple.dt.Xcode IDEEditorCoordinatorTarget_Click -string "FocusedEditor"
# }}}

# Print {{{
info "Print"
substep_info "Automatically quit printer app once the print jobs complete"
  defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
# }}}

# Time Machine {{{
info "Time Machine"
substep_info "Prevent from prompting to use new hard drives as backup volume"
  defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
# }}}

# Photos {{{
info "Photos"
substep_info "Prevent from opening automatically when devices are plugged in"
  defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
# }}}

### Third Party Apps ###

# Tweetbot {{{
info "Tweetbot"
substep_info "Bypass t.co URL shortener"
  defaults write com.tapbots.TweetbotMac OpenURLsDirectly -bool true
# }}}

# Itsycal {{{
info "Itsycal"
substep_info "Configure display"
  defaults write com.mowglii.ItsycalApp ClockFormat -string "h:mm a"
  defaults write com.mowglii.ItsycalApp ShowMonthInIcon -bool true
  defaults write com.mowglii.ItsycalApp ShowDayOfWeekInIcon -bool true
# }}}

# VS Code {{{
info "VS Code"
substep_info "Allow key repeat for Vim"
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
# }}}

for app in "cfprefsd" \
	"Dock" \
	"Finder" \
	"Itsycal" \
	"Mail" \
	"Messages" \
	"Photos" \
	"Safari" \
	"SystemUIServer" \
	"Terminal" \
	"Tweetbot" \
	"iCal"; do
	killall "${app}" &> /dev/null
done

success "Done. Note that some of these changes require a logout/restart to take effect."
